config/routes.rb
Rails.application.routes.draw do

  get 'main/index'

  get 'main/about'

  get 'main/secret'

  root 'main#index'

  get 'about' => 'main#about'
  get 'secret' => 'main#secret'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'

  get 'logout' => 'sessions#destroy'

  get 'signup' => 'users#new'
  post 'signup' => 'users#create'

  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  validates :email,
  presence: true,
  uniqueness: {case_sensitive:false},
  # format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i,message: "valid email"}
  format: { with: /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/,message: "valid email"}

  validates_presence_of :password, on: :create

  validates :name, length: { maximum: 20 }

  has_many :posts

  def self.authenticate email, password
    User.find_by_email(email).try(:authenticate, password)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :current_user

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def is_authenticated?
   unless @current_user
      flash[:danger] = 'ACCESS DENIED!!!!'
      redirect_to login_path
    end
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController

  before_action :is_authenticated?, only: [:secret]
  # before_action :is_authenticated?, except: [:index]


  def index
  end

  def about
  end

  def secret
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


  def index
    @posts = Post.all
  end



  def show
    @post = Post.find params[:id]
    # puts params
    # render json: params
  end

  def new
    @post = Post.new
  end

  def create
    # render json: params
    Post.create post_params
    redirect_to posts_path
  end

  def edit
    @post = Post.find params[:id]
  end

  def update
    # render json: params
    t = Post.find params[:id]
    t.update post_params
    redirect_to posts_path
  end

  def destroy
    # render json: params
    Post.find(params[:id]).delete
    redirect_to posts_path
  end

   private

  def post_params
    params.require(:post).permit(:title,:link)
  end




end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # login form
  def new
    # render plain: "new session"
  end

  # login action (create a session)
  def create
    # render plain: "create session"
    # render json: params
    user = User.authenticate(params[:user][:email],params[:user][:password])
    if user
      # correct email / password
      session[:user_id] = user.id
      flash[:success] = 'You are now logged in.'
      redirect_to posts_path
    else
      # wrong email or password
      flash[:danger] = 'Invalid email or password.'
      redirect_to login_path
      # render :new
    end
  end

  # logout action (invalidates the session)
  def destroy
    # render plain: "destroy session"
    session[:user_id] = nil
    flash[:info] = "You are loggged out."
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    # render json: user_params
    user = User.new user_params
    user.save
    # correct email / password
    session[:user_id] = user.id
    flash[:success] = 'You are now logged in.'
    redirect_to posts_path
  end

   private

  def user_params
    params.require(:user).permit(:email,:password,:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>hackNews!</title>
  <!-- Latest compiled and minified CSS & JS -->
  <link rel="stylesheet" media="screen" href="//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <script src="//code.jquery.com/jquery.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="row">
    <h1>Logo</h1>
    <div class="pull-right">

      <% if @current_user %>
        Welcome back <%= @current_user.name %>
        <%= link_to "logout", logout_path %>
      <% else %>
        <p><%= link_to "login", login_path %></p>
        <p><%= link_to "signup", signup_path %></p>
      <% end %>

    </div>
  </div>
  <div class="row">
    <%= yield %>
  </div>

</div>

</body>
</html>

app/views/main/about.html.erb
<h1>Main#about</h1>
<p>Find me in app/views/main/about.html.erb</p>

app/views/main/index.html.erb
<%= render "shared/flash" %>


<h1>hackNews</h1>
<p>Find me in app/views/main/index.html.erb</p>

app/views/main/secret.html.erb
<h1>Welcome to Hack News Member Area</h1>
<p>Find me in app/views/main/secret.html.erb</p>

app/views/posts/_form.html.erb
<%= form_for @post, url: {action: form_action}, html: {class: "form-control"} do |f| %>

<div class="row">
  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
    <%= label_tag(:title, "Enter Post Title") %>
  </div>
  <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9">
    <%= f.text_field :title %>
  </div>
</div>
<div class="row">
  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
    <%= label_tag(:link, "Enter link of Post") %>
  </div>
  <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9">
    <%= f.text_field :link %>
  </div>
</div>
<div class="row pull-right">
  <%= f.submit form_action.capitalize %>
</div>

<% end %>

app/views/posts/edit.html.erb
<h3>Edit a Post</h3>


<%= render partial: "form", locals: {form_action: "update"} %>

app/views/posts/index.html.erb
<div class="row">
  <h2>Post List</h2>

  <%= link_to " Create New Post", new_post_path, class: 'btn btn-primary btn-xs glyphicon glyphicon-plus pull-right' %>
</div>


<% @posts.each do |post| %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= link_to post.title, post %></h3>
  </div>
  <div class="panel-body">
    <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
      <%= post.link %>
    </div>
    <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2 pull-right">
      <%= link_to "", edit_post_path(post), class: 'btn btn-primary btn-xs glyphicon glyphicon-pencil' %>
      <%= link_to "", post, method: :delete, class: 'btn btn-danger btn-xs glyphicon glyphicon-trash' %>
    </div>
  </div>
</div>

<% end %>

app/views/posts/new.html.erb
<h3>Create a Post</h3>

<%= render partial: "form", locals: {form_action: "create"} %>

app/views/posts/show.html.erb
<h3>A POST</h3>

<div class="row">
  <%= link_to "&larr; back".html_safe, posts_path %>

</div>


<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= @post.title %></h3>
  </div>
  <div class="panel-body">
    <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
      <p><%= @post.link %></p>
      Posted At: <%= @post.created_at %>  by: <%= @post.user.name %>
    </div>
  </div>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |k,v| %>
  <div class="alert alert-<%= k %>">
    <%= v %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Create an Account</h1>

<%= render "shared/flash" %>

<%= bootstrap_form_for :user do |f| %>
  <%= f.text_field :email, placeholder: "Enter your email" %>
  <%= f.password_field :password, placeholder: "Enter your password"%>
  <%= f.text_field :name, placeholder: "Enter your name"%>
  <%= f.submit "Login"%>
<% end %>